

services:
  app:
    build:
      context: .
    image: laravel-app
    container_name: laravel-app
    ports:
      - "9000:9000"
    volumes:
      - .:/var/www
    networks:
      - laravel
    command: >
        sh -c "composer install &&
        cp .env.example .env &&
        php artisan key:generate &&
        php artisan migrate &&
        npm install &&
        npm run build &&
        php-fpm"


  webserver:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - .:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel

  db:
    image: mysql:5.7
    container_name: mysql
    platform: linux/amd64
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: votesmash
      MYSQL_ROOT_PASSWORD: root

    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - laravel

volumes:
  dbdata:

networks:
  laravel:
